# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdvancedNetwork():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_advancedNetwork(self):
    # Test name: advancedNetwork
    # Step # | name | target | value
    # 1 | open | http://192.168.0.1 | 
    self.driver.get("http://192.168.0.1")
    # 2 | setWindowSize | 1243x969 | 
    self.driver.set_window_size(1243, 969)
    # 3 | type | name=input-password-field | 000000
    self.driver.find_element(By.NAME, "input-password-field").send_keys("000000")
    # 4 | sendKeys | name=input-password-field | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "input-password-field").send_keys(Keys.ENTER)
    # 5 | click | css=.header-status:nth-child(1) .menu-icon-header | 
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".header-status:nth-child(1) .menu-icon-header").click()
    # 6 | click | css=.has-child-menu:nth-child(6) > .el-submenu__title | 
    self.driver.find_element(By.CSS_SELECTOR, ".has-child-menu:nth-child(6) > .el-submenu__title").click()
    # 7 | click | css=.is-opened .el-menu-item:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .el-menu-item:nth-child(1) > span").click()
    # 8 | click | css=.wrap-form-card:nth-child(2) .el-switch__core | 
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(2) .el-switch__core").click()
    # 9 | pause | 5 | 
    time.sleep(10)
    # 10 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 11 | pause | 5 | 
    time.sleep(10)
    # 12 | click | css=.wrap-form-card:nth-child(2) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(2) .el-switch__core").click()
    # 13 | pause | 5 | 
    time.sleep(10)
    # 14 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 15 | pause | 5 | 
    time.sleep(10)
    # 16 | click | css=.wrap-form-card:nth-child(3) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(3) .el-switch__core").click()
    # 17 | pause | 5 | 
    time.sleep(10)
    # 18 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 19 | pause | 5 | 
    time.sleep(10)
    # 20 | click | css=.wrap-form-card:nth-child(3) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(3) .el-switch__core").click()
    # 21 | pause | 5 | 
    time.sleep(10)
    # 22 | click | css=.apply | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply").click()
    # 23 | pause | 5 | 
    time.sleep(10)
    # 24 | click | css=.wrap-form-card:nth-child(4) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(4) .el-switch__core").click()
    # 25 | pause | 5 | 
    time.sleep(10)
    # 26 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 27 | pause | 5 | 
    time.sleep(10)
    # 28 | click | css=.wrap-form-card:nth-child(4) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(4) .el-switch__core").click()
    # 29 | pause | 5 | 
    time.sleep(10)
    # 30 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 31 | pause | 5 | 
    time.sleep(10)
    # 32 | click | css=.wrap-form-card:nth-child(5) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(5) .el-switch__core").click()
    # 33 | pause | 5 | 
    time.sleep(10)
    # 34 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 35 | pause | 5 | 
    time.sleep(10)
    # 36 | click | css=.wrap-form-card:nth-child(5) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(5) .el-switch__core").click()
    # 37 | pause | 5 | 
    time.sleep(10)
    # 38 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 39 | pause | 5 | 
    time.sleep(10)
    # 40 | click | css=.wrap-form-card:nth-child(6) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(6) .el-switch__core").click()
    # 41 | pause | 5 | 
    time.sleep(10)
    # 42 | click | css=.apply | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply").click()
    # 43 | pause | 5 | 
    time.sleep(10)
    # 44 | click | css=.wrap-form-card:nth-child(6) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(6) .el-switch__core").click()
    # 45 | pause | 5 | 
    time.sleep(10)
    # 46 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 47 | pause | 5 | 
    time.sleep(15)
    # 48 | click | css=.wrap-form-card:nth-child(7) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(7) .el-switch__core").click()
    # 49 | pause | 5 | 
    time.sleep(10)
    # 50 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
    # 51 | pause | 5 | 
    time.sleep(10)
    # 52 | click | css=.wrap-form-card:nth-child(7) .el-switch__core | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrap-form-card:nth-child(7) .el-switch__core").click()
    # 53 | pause | 5 | 
    time.sleep(10)
    # 54 | click | css=.apply > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".apply > span").click()
  
  